# CS446/519 Class Session 5 - Exercise
## Exploring the running time for testing if there is an edge between a pair of vertices

## Assignment for today (based on the key concept of Newman 9.5)

Today we will be exploring the computational running time for testing whether a pair of vertices has an edge between them (averaged over all vertex pairs), for different data structures for storing the graph (adjacency matrix, adjacency list, edge list, and "adjacency forest" (which Newman calls the "adjacency tree").

This exercise is a straightforward generalization of the exercise from Class Session 4, but you'll need a new data structure to handle the "adjacency forest". Note for R users: in R, we will have to cheat by using an `environment` data structure (which is not implemented using a binary search tree but rather, a hash table). In this exercise, we'll try varying the graph's average vertex degree ($k$) while keeping the total number of vertices fixed at $n=1000$.

To get started, you will need to write four functions:

- `find_adj_matrix(adj_matrix, i, j)`
    - returns `True` if `i` and `j` are directly connected in the network described by the adjacency matrix
`adj_matrix`, or `False` otherwise.
- `find_adj_list(adj_list, i, j)`
    - returns `True` if `i` and `j` are directly connected in the network described by the adjacency list `adj_list`, or `False` otherwise
- `find_edge_list(edge_list, i, j)`
    - returns `True` if `i` and `j` are directly connected in the network described by the edge list `edge_list`, or `False` otherwise. (Note: I opted not to do any timing on `find_edge_list` because the code was running quite slow, but you can try it if you are more patient than I am).
- `find_adj_forest(adj_forest, i, j)`
    - returns `True` if `i` and `j` are directly connected in the network described by the "adjacency forest" `adj_forest`, or `False` otherwise. 
    - The adjacency forest can be a list of AVL binary search trees (using the `AVLTree` class from the `bintrees` python package), or it can be a list of dictionary data types (which is slightly different from the binary search tree suggested in Newman 9.5, but still useful for this exercise).


In this exercise, we'll compare the asymptotic computational running time for testing if there is an edge between a pair of vertices, averaged over all the vertices in the graph. We'll do it for an undirected graph (Barabasi-Albert model) with an average vertex degree that will be fixed for a given graph but that we will vary. The  number of vertices of the graph will be fixed at 1000.

We'll need the "bintrees" package in order to get an implementation of a binary search tree (AVLTree is the class that we will use).

In [1]:
import numpy as np
import igraph
import timeit
import itertools
import bintrees 

The next four functions show how to test whether a given pair of vertices has an edge between them:

In [2]:
def find_matrix(gmat, i, j):
    return (gmat[i,j] == 1)

In [3]:
def find_adj_list(adj_list, i, j):
    return j in adj_list[i]

In [4]:
def find_edge_list(edge_list, i, j):
    inds1 = np.where(edge_list[:,0] == i)[0]
    elems1 = edge_list[inds1, 1].tolist()
    inds2 = np.where(edge_list[:,1] == i)[0]
    elems2 = edge_list[inds2, 0].tolist()
    return j in (elems1 + elems2)

In [5]:
def find_bst_forest(bst_forest, i, j):
    return bst_forest[i].__contains__(j)

This function takes a graph in adjacency list format and makes an "adjacency forest" data structure.

In [8]:
def get_bst_forest(theadjlist):
    g_adj_list = theadjlist
    n = len(g_adj_list)
    theforest = []
    for i in range(0,n):        
        itree = bintrees.AVLTree()
        for j in g_adj_list[i]:
            itree.insert(j, None)
        theforest.append(itree)
    return theforest

def get_bst_forest2(theadjlist):
    n = len(theadjlist)
    for i in range(0, n):
        m = len(theadjlist[i])
        values = [None] * m
        pairs = [*zip(theadjlist[i], values)]
        itree = bintrees.AVLTree(pairs)
        
        yield itree

g = igraph.Graph.Barabasi(5, 2)
g_adj_list = g.get_adjlist()
        
g_bst_forest1 = get_bst_forest(g_adj_list)
g_bst_forest2 = [*get_bst_forest2(g_adj_list)]

print(g_adj_list)
print(g_bst_forest1)
print(g_bst_forest2)

[[1, 2, 3, 4], [0, 2], [0, 1, 3], [0, 2, 4], [0, 3]]
[AVLTree({1: None, 2: None, 3: None, 4: None}), AVLTree({0: None, 2: None}), AVLTree({0: None, 1: None, 3: None}), AVLTree({0: None, 2: None, 4: None}), AVLTree({0: None, 3: None})]
[AVLTree({1: None, 2: None, 3: None, 4: None}), AVLTree({0: None, 2: None}), AVLTree({0: None, 1: None, 3: None}), AVLTree({0: None, 2: None, 4: None}), AVLTree({0: None, 3: None})]


Here is the code to run the simulation (generate the graph and obtain timing statistics). To keep the code running time reasonable, I decided to only compare the running times for the "adjacency list" and "adjacency forest" (aka "adjacency trees") graph data structures.  The parameter "n" is the number of vertices (fixed at 1000) and the parameter "k" is the average vertex degree (which we will vary in this exercise). For speed, I have turned off replication (by setting nrep=1 and nsubrep=1), but you can try it with larger values of nrep to see if the results hold up (I expect they will):

In [9]:
def do_sim(n, k):

    retlist = []
    
    nrep = 1
    nsubrep = 1
    
    for _ in itertools.repeat(None, nrep):
      
        # make the random undirected graph
        g = igraph.Graph.Barabasi(n, k)
        
        # get the graph in three different representations
        g_adj_list = g.get_adjlist()
        
        g_bst_forest = get_bst_forest(g_adj_list)
        
        start_time = timeit.default_timer()
        
        # inner loop only needs to go from i+1 to n, since the graph is undirected        
        for _ in itertools.repeat(None, nsubrep):
            for i in range(0, n):
                for j in range(i+1, n):
                    find_adj_list(g_adj_list, i, j)     
        
        adjlist_elapsed = timeit.default_timer() - start_time
            
        start_time = timeit.default_timer()
        
        # inner loop only needs to go from i+1 to n, since the graph is undirected
        for _ in itertools.repeat(None, nsubrep):
            for i in range(0, n):
                for j in range(i+1, n):
                    j in g_bst_forest[i]
                    
        forest_elapsed = timeit.default_timer() - start_time
        
        retlist.append([adjlist_elapsed, forest_elapsed])

        # get the results in microseconds, and make sure to divide by number of vertex pairs
    return 1000000*np.mean(np.array(retlist), axis=0)/(n*(n-1)/2)

Compare the results for differing average degree (i.e., k) values.  At k=50, the "adjacency forest" method (aka "adjacency tree" method) is a bit faster than the adjacency list method. By k=100, the "adjacency forest" method is substantially faster than the "adjacency list" method.

In [10]:
do_sim(1000,5)

array([ 0.3204156 ,  1.16994051])

In [11]:
do_sim(1000,10)

array([ 0.51273477,  1.26613626])

In [12]:
do_sim(1000,20)

array([ 0.873007  ,  1.38149768])

In [13]:
do_sim(1000,50)

array([ 1.83869825,  1.50265984])

In [14]:
do_sim(1000,100)

array([ 3.19050297,  1.56077285])